### ISSUE TITLE
'Car' is unavailable with Xcode 7.2

### ISSUE THREAD

**Issue by stevemoser** [andrewcbancroft/CoreDataFrameworkExample#1]
I ran the converter on the framework and the project and I get 

```
'Car' is unavailable: cannot find Swift declaration for this class
```

error. Any idea on how to fix this? I'm running into a similar issue with my own project.

**Comment by andrewcbancroft** [comment]
I'll try and check it out this week, Steve.  Thanks for reporting the issue!

**Comment by andrewcbancroft** [comment]
Hey Steve - I updated the projects today for compatibility with Xcode 7 and Swift 2.  I tried to verify that things were working by downloading a fresh .zip from the repo and things built and ran fine for me.  Closing this issue, but if you experience trouble still, please holler and I'll take another look.  Thanks again for alerting me to the incompatibility!

**Comment by stevemoser** [comment]
Thanks! It works for me now. I'll have to look into what I did differently.
